version: "3.7"

volumes:
  cache:

services:
  server:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: keypoints
    restart: "no"
    volumes:
      - ".:/app"
      - "cache:/home/user/.cache"

